### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by mkomod**
Correction

### CODE REVIEW

**Review by RangerMauve — APPROVED** [review]

**Comment by ghost** [comment]
Thank you for fixing this @mkomod, and thank you @RangerMauve for reviewing it!

Please feel free to just go ahead and merge changes like this in the future. I trust the judgment of everyone in the datprotocol team and I don't want to be the bottleneck that keeps good pull requests waiting!

**Comment by RangerMauve** [comment]
Sadly I don't have permission to merge yet. :P cc @joehand

**Comment by ghost** [comment]
Ok! I have updated this repo's settings to allow the datprotocol team to write to it and also sent you an invite @RangerMauve.

**Comment by RangerMauve** [comment]
Sweet, thank you! :)

**Pull request merged**
